server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - argocd.guled.co.uk
    tls:
      - hosts:
          - argocd.guled.co.uk
        secretName: argocd-tls
  service:
    port: 443  
    targetPort: 8080
  extraArgs: []  

config:
  url: https://argocd.guled.co.uk
