server:
  ingress:
    enabled: true
    ingressClassName: nginx   
    hostname: argocd.guled.co.uk
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - hosts:
          - argocd.guled.co.uk
        secretName: argocd-tls

configs:
  params:
    server.insecure: true
    server.grpc-web: true

