provider: cloudflare

cloudflare:
  apiTokenSecretRef:
    name: cloudflare-api-token-secret
    key: api-token
  proxied: false

sources:
  - ingress

domainFilters:
  - guled.co.uk

policy: upsert-only
registry: txt
txtOwnerId: youtube-aks
logLevel: info
