controller:
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /health
    externalTrafficPolicy: Local
    type: LoadBalancer

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

defaultBackend:
  enabled: true
