apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtube-clone
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Guled-Mahamud/aks-youtube-clone
    targetRevision: HEAD
    path: k8s-manifests/charts/youtube-clone
    helm:
      valueFiles:
        - ../../helm-values/youtube-clone-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: youtube
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
