apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: guledm92@hotmail.co.uk
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    solvers:
      - dns01:
          cloudflare:
            email: guledm92@hotmail.co.uk
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
