prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 30s
    evaluationInterval: 30s
    retention: 7d
    enableAdminAPI: true
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - prometheus.guled.co.uk
      tls:
        - hosts:
            - prometheus.guled.co.uk
          secretName: prometheus-tls

grafana:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.guled.co.uk
    tls:
      - hosts:
          - grafana.guled.co.uk
        secretName: grafana-tls

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
