prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 30s
    evaluationInterval: 30s
    retention: 7d
    enableAdminAPI: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - prometheus.guled.co.uk
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.guled.co.uk

grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - grafana.guled.co.uk
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.guled.co.uk

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
