image:
  repository: youtubeclone.azurecr.io/youtube-clone
  tag: v1
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: youtube.guled.co.uk
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - youtube.guled.co.uk
      secretName: youtube-tls
