name: Build, Scan, and Push Docker Image to ACR

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'app/**'

permissions:
  id-token: write
  contents: read

env:
  ACR_SERVER: youtubeclone.azurecr.io
  DOCKER_IMAGE_NAME: youtube-clone

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production   
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (SP via JSON)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify required secrets are set
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        run: |
          for v in ARM_CLIENT_ID ARM_CLIENT_SECRET; do
            if [ -z "${!v}" ]; then echo "::error::Missing secret: $v"; exit 1; fi
          done

      - name: ACR login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_SERVER }}
          username: ${{ secrets.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Build image (load for scan)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
          load: true

      - name: Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.run_number }}
            ${{ env.ACR_SERVER }}/${{ env.DOCKER_IMAGE_NAME }}:latest
